import type { Linter } from 'eslint';

const vueRules = {
  'vue/array-bracket-newline': ['off'],
  'vue/array-bracket-spacing': ['off'],
  'vue/array-element-newline': ['off'],
  'vue/arrow-spacing': ['off'],
  'vue/attribute-hyphenation': ['error'],
  'vue/attributes-order': ['error'],
  'vue/block-lang': ['off'],
  'vue/block-order': ['error'],
  'vue/block-spacing': ['off'],
  'vue/block-tag-newline': ['off'],
  'vue/brace-style': ['off'],
  'vue/camelcase': [
    'error',
    {
      properties: 'never'
    }
  ],
  'vue/comma-dangle': ['off'],
  'vue/comma-spacing': ['off'],
  'vue/comma-style': ['off'],
  'vue/comment-directive': ['error'],
  'vue/component-api-style': [
    'error',
    ['script-setup', 'composition']
  ],
  'vue/component-definition-name-casing': ['error'],
  'vue/component-name-in-template-casing': [
    'error',
    'PascalCase'
  ],
  'vue/component-options-name-casing': ['error'],
  'vue/custom-event-name-casing': [
    'error',
    'camelCase'
  ],
  'vue/define-emits-declaration': [
    'error',
    'type-based'
  ],
  'vue/define-macros-order': [
    'error',
    {
      order: [
        'defineOptions',
        'defineModel',
        'defineProps',
        'defineEmits',
        'defineSlots'
      ]
    }
  ],
  'vue/define-props-declaration': [
    'error',
    'type-based'
  ],
  'vue/define-props-destructuring': [
    'error',
    { destructure: 'always' }
  ],
  'vue/dot-location': ['off'],
  'vue/dot-notation': ['error'],
  'vue/enforce-style-attribute': ['off'],
  'vue/eqeqeq': [
    'error',
    'always'
  ],
  'vue/first-attribute-linebreak': ['error'],
  'vue/func-call-spacing': ['off'],
  'vue/html-button-has-type': [
    'error',
    {
      button: true,
      reset: true,
      submit: true
    }
  ],
  'vue/html-closing-bracket-newline': ['error'],
  'vue/html-closing-bracket-spacing': ['error'],
  'vue/html-comment-content-newline': ['off'],
  'vue/html-comment-content-spacing': ['off'],
  'vue/html-comment-indent': ['off'],
  'vue/html-end-tags': ['error'],
  'vue/html-indent': ['error'],
  'vue/html-quotes': ['error'],
  'vue/html-self-closing': ['error'],
  'vue/jsx-uses-vars': ['error'],
  'vue/key-spacing': ['off'],
  'vue/keyword-spacing': ['off'],
  'vue/match-component-file-name': ['off'],
  'vue/match-component-import-name': ['error'],
  'vue/max-attributes-per-line': ['error'],
  'vue/max-len': ['off'],
  'vue/max-lines-per-block': ['off'],
  'vue/max-props': ['off'],
  'vue/max-template-depth': ['off'],
  'vue/multi-word-component-names': ['error'],
  'vue/multiline-html-element-content-newline': ['error'],
  'vue/multiline-ternary': ['off'],
  'vue/mustache-interpolation-spacing': ['error'],
  'vue/new-line-between-multi-line-property': ['off'],
  'vue/next-tick-style': ['error'],
  'vue/no-arrow-functions-in-watch': ['error'],
  'vue/no-async-in-computed-properties': ['error'],
  'vue/no-bare-strings-in-template': ['off'],
  'vue/no-boolean-default': ['off'],
  'vue/no-child-content': ['error'],
  'vue/no-computed-properties-in-data': ['error'],
  'vue/no-console': ['error'],
  'vue/no-constant-condition': ['error'],
  'vue/no-custom-modifiers-on-v-model': ['off'],
  'vue/no-deprecated-data-object-declaration': ['error'],
  'vue/no-deprecated-delete-set': ['error'],
  'vue/no-deprecated-destroyed-lifecycle': ['error'],
  'vue/no-deprecated-dollar-listeners-api': ['error'],
  'vue/no-deprecated-dollar-scopedslots-api': ['error'],
  'vue/no-deprecated-events-api': ['error'],
  'vue/no-deprecated-filter': ['error'],
  'vue/no-deprecated-functional-template': ['error'],
  'vue/no-deprecated-html-element-is': ['error'],
  'vue/no-deprecated-inline-template': ['error'],
  'vue/no-deprecated-model-definition': ['error'],
  'vue/no-deprecated-props-default-this': ['error'],
  'vue/no-deprecated-router-link-tag-prop': ['error'],
  'vue/no-deprecated-scope-attribute': ['error'],
  'vue/no-deprecated-slot-attribute': ['error'],
  'vue/no-deprecated-slot-scope-attribute': ['error'],
  'vue/no-deprecated-v-bind-sync': ['error'],
  'vue/no-deprecated-v-is': ['error'],
  'vue/no-deprecated-v-on-native-modifier': ['error'],
  'vue/no-deprecated-v-on-number-modifiers': ['error'],
  'vue/no-deprecated-vue-config-keycodes': ['error'],
  'vue/no-dupe-keys': ['error'],
  'vue/no-dupe-v-else-if': ['error'],
  'vue/no-duplicate-attr-inheritance': ['error'],
  'vue/no-duplicate-attributes': ['error'],
  'vue/no-duplicate-class-names': ['error'],
  'vue/no-empty-component-block': ['error'],
  'vue/no-empty-pattern': ['error'],
  'vue/no-export-in-script-setup': ['error'],
  'vue/no-expose-after-await': ['error'],
  'vue/no-extra-parens': ['off'],
  'vue/no-implicit-coercion': ['error'],
  'vue/no-import-compiler-macros': ['error'],
  'vue/no-irregular-whitespace': ['error'],
  'vue/no-lifecycle-after-await': ['error'],
  'vue/no-literals-in-template': ['off'],
  'vue/no-lone-template': ['error'],
  'vue/no-loss-of-precision': ['error'],
  'vue/no-multi-spaces': ['off'],
  'vue/no-multiple-objects-in-class': ['error'],
  'vue/no-multiple-slot-args': ['error'],
  'vue/no-multiple-template-root': ['off'],
  'vue/no-mutating-props': ['error'],
  'vue/no-negated-condition': ['off'],
  'vue/no-negated-v-if-condition': ['error'],
  'vue/no-parsing-error': ['error'],
  'vue/no-potential-component-option-typo': ['error'],
  'vue/no-ref-as-operand': ['error'],
  'vue/no-ref-object-reactivity-loss': ['error'],
  'vue/no-required-prop-with-default': ['error'],
  'vue/no-reserved-component-names': ['error'],
  'vue/no-reserved-keys': ['error'],
  'vue/no-reserved-props': ['error'],
  'vue/no-restricted-block': ['off'],
  'vue/no-restricted-call-after-await': ['off'],
  'vue/no-restricted-class': ['off'],
  'vue/no-restricted-component-names': ['off'],
  'vue/no-restricted-component-options': ['off'],
  'vue/no-restricted-custom-event': ['off'],
  'vue/no-restricted-html-elements': ['off'],
  'vue/no-restricted-props': ['off'],
  'vue/no-restricted-static-attribute': ['off'],
  'vue/no-restricted-syntax': ['off'],
  'vue/no-restricted-v-bind': ['off'],
  'vue/no-restricted-v-on': ['off'],
  'vue/no-root-v-if': ['off'],
  'vue/no-setup-props-reactivity-loss': ['error'],
  'vue/no-shared-component-data': ['error'],
  'vue/no-side-effects-in-computed-properties': ['error'],
  'vue/no-spaces-around-equal-signs-in-attribute': ['error'],
  'vue/no-sparse-arrays': ['error'],
  'vue/no-static-inline-styles': ['off'],
  'vue/no-template-key': ['error'],
  'vue/no-template-shadow': ['error'],
  'vue/no-template-target-blank': ['error'],
  'vue/no-textarea-mustache': ['error'],
  'vue/no-this-in-before-route-enter': ['error'],
  'vue/no-undef-components': ['off'],
  'vue/no-undef-directives': ['error'],
  'vue/no-undef-properties': ['off'],
  'vue/no-unsupported-features': ['off'],
  'vue/no-unused-components': ['error'],
  'vue/no-unused-emit-declarations': ['error'],
  'vue/no-unused-properties': ['error'],
  'vue/no-unused-refs': ['error'],
  'vue/no-unused-vars': ['error'],
  'vue/no-use-computed-property-like-method': ['error'],
  'vue/no-use-v-else-with-v-for': ['error'],
  'vue/no-use-v-if-with-v-for': ['error'],
  'vue/no-useless-concat': ['error'],
  'vue/no-useless-mustaches': ['error'],
  'vue/no-useless-template-attributes': ['error'],
  'vue/no-useless-v-bind': ['error'],
  'vue/no-v-for-template-key-on-child': ['error'],
  'vue/no-v-html': ['error'],
  'vue/no-v-text': ['off'],
  'vue/no-v-text-v-html-on-component': ['error'],
  'vue/no-watch-after-await': ['error'],
  'vue/object-curly-newline': ['off'],
  'vue/object-curly-spacing': ['off'],
  'vue/object-property-newline': ['off'],
  'vue/object-shorthand': [
    'error',
    'always'
  ],
  'vue/one-component-per-file': ['error'],
  'vue/operator-linebreak': ['off'],
  'vue/order-in-components': ['error'],
  'vue/padding-line-between-blocks': ['off'],
  'vue/padding-line-between-tags': ['off'],
  'vue/padding-lines-in-component-definition': ['off'],
  'vue/prefer-define-options': ['error'],
  'vue/prefer-import-from-vue': ['error'],
  'vue/prefer-prop-type-boolean-first': ['error'],
  'vue/prefer-separate-static-class': ['error'],
  'vue/prefer-single-event-payload': ['error'],
  'vue/prefer-template': ['error'],
  'vue/prefer-true-attribute-shorthand': ['error'],
  'vue/prefer-use-template-ref': ['error'],
  'vue/prefer-v-model': ['error'],
  'vue/prop-name-casing': ['error'],
  'vue/quote-props': ['off'],
  'vue/require-component-is': ['error'],
  'vue/require-default-export': ['error'],
  'vue/require-default-prop': ['error'],
  'vue/require-direct-export': ['off'],
  'vue/require-emit-validator': ['error'],
  'vue/require-explicit-emits': ['error'],
  'vue/require-explicit-slots': ['error'],
  'vue/require-expose': ['off'],
  'vue/require-macro-variable-name': [
    'error',
    {
      defineEmits: 'emit',
      defineProps: 'props',
      defineSlots: 'slots',
      useAttrs: 'attrs',
      useSlots: 'slots'
    }
  ],
  'vue/require-name-property': ['off'],
  'vue/require-prop-comment': ['off'],
  'vue/require-prop-type-constructor': ['error'],
  'vue/require-prop-types': ['error'],
  'vue/require-render-return': ['error'],
  'vue/require-slots-as-functions': ['error'],
  'vue/require-toggle-inside-transition': ['error'],
  'vue/require-typed-object-prop': ['error'],
  'vue/require-typed-ref': ['error'],
  'vue/require-v-for-key': ['error'],
  'vue/require-valid-default-prop': ['error'],
  'vue/restricted-component-names': ['off'],
  'vue/return-in-computed-property': ['error'],
  'vue/return-in-emits-validator': ['error'],
  'vue/script-indent': ['off'],
  'vue/singleline-html-element-content-newline': ['error'],
  'vue/slot-name-casing': ['error'],
  'vue/sort-keys': ['off'],
  'vue/space-in-parens': ['off'],
  'vue/space-infix-ops': ['off'],
  'vue/space-unary-ops': ['off'],
  'vue/static-class-names-order': ['off'],
  'vue/template-curly-spacing': ['off'],
  'vue/this-in-template': ['error'],
  'vue/use-v-on-exact': ['error'],
  'vue/v-bind-style': ['error'],
  'vue/v-for-delimiter-style': [
    'error',
    'in'
  ],
  'vue/v-if-else-key': ['error'],
  'vue/v-on-event-hyphenation': ['error'],
  'vue/v-on-handler-style': [
    'error',
    ['method', 'inline-function']
  ],
  'vue/v-on-style': ['error'],
  'vue/v-slot-style': ['error'],
  'vue/valid-attribute-name': ['error'],
  'vue/valid-define-emits': ['error'],
  'vue/valid-define-options': ['error'],
  'vue/valid-define-props': ['error'],
  'vue/valid-next-tick': ['error'],
  'vue/valid-template-root': ['error'],
  'vue/valid-v-bind': ['error'],
  'vue/valid-v-cloak': ['error'],
  'vue/valid-v-else': ['error'],
  'vue/valid-v-else-if': ['error'],
  'vue/valid-v-for': ['error'],
  'vue/valid-v-html': ['error'],
  'vue/valid-v-if': ['error'],
  'vue/valid-v-is': ['error'],
  'vue/valid-v-memo': ['error'],
  'vue/valid-v-model': ['error'],
  'vue/valid-v-on': ['error'],
  'vue/valid-v-once': ['error'],
  'vue/valid-v-pre': ['error'],
  'vue/valid-v-show': ['error'],
  'vue/valid-v-slot': ['error'],
  'vue/valid-v-text': ['error']
} satisfies Linter.Config['rules'];

export default vueRules;
