import type { Linter } from 'eslint';

const eslintRules = {
  'array-callback-return': [
    'error',
    {
      allowImplicit: true,
      checkForEach: true
    }
  ],
  'constructor-super': ['error'],
  'for-direction': ['error'],
  'getter-return': ['error'],
  'no-async-promise-executor': ['error'],
  'no-await-in-loop': ['off'],
  'no-class-assign': ['error'],
  'no-compare-neg-zero': ['error'],
  'no-cond-assign': ['error', 'except-parens'],
  'no-const-assign': ['error'],
  'no-constant-binary-expression': ['error'],
  'no-constant-condition': [
    'error',
    {
      checkLoops: 'allExceptWhileTrue'
    }
  ],
  'no-constructor-return': ['error'],
  'no-control-regex': ['error'],
  'no-debugger': ['error'],
  'no-dupe-args': ['error'],
  'no-dupe-class-members': ['error'],
  'no-dupe-else-if': ['error'],
  'no-dupe-keys': ['error'],
  'no-duplicate-case': ['error'],
  'no-duplicate-imports': ['error'], // Does this have a version with autofix?
  'no-empty-character-class': ['error'],
  'no-empty-pattern': ['error'],
  'no-ex-assign': ['error'],
  'no-fallthrough': ['error'],
  'no-func-assign': ['error'],
  'no-import-assign': ['error'],
  'no-inner-declarations': ['error'],
  'no-invalid-regexp': ['error'],
  'no-irregular-whitespace': ['error'],
  'no-loss-of-precision': ['error'],
  'no-misleading-character-class': ['error'],
  'no-new-native-nonconstructor': ['error'],
  'no-obj-calls': ['error'],
  'no-promise-executor-return': ['error'],
  'no-prototype-builtins': ['error'],
  'no-self-assign': ['error'],
  'no-self-compare': ['error'],
  'no-setter-return': ['error'],
  'no-sparse-arrays': ['error'],
  'no-template-curly-in-string': ['error'],
  'no-this-before-super': ['error'],
  'no-unassigned-vars': ['error'],
  'no-undef': ['error'],
  'no-unexpected-multiline': ['error'],
  'no-unmodified-loop-condition': ['error'],
  'no-unreachable': ['error'],
  'no-unreachable-loop': ['error'],
  'no-unsafe-finally': ['error'],
  'no-unsafe-negation': [
    'error',
    {
      enforceForOrderingRelations: true
    }
  ],
  'no-unsafe-optional-chaining': [
    'error',
    {
      disallowArithmeticOperators: true
    }
  ],
  'no-unused-private-class-members': ['error'],
  'no-unused-vars': ['error', 'all'], // Should the option be 'all'?
  'no-use-before-define': [
    'error',
    {
      allowNamedExports: false,
      classes: true,
      functions: false,
      variables: true
    }
  ]
} satisfies Linter.Config['rules'];

const eslintSuggestionsRules = {
  'accessor-pairs': ['error'],
  'arrow-body-style': ['error', 'as-needed'],
  'block-scoped-var': ['error'],
  camelcase: ['error'], // Should this be enabled?
  'capitalized-comments': ['off'],
  'class-methods-use-this': ['error'],
  complexity: ['error', 30],
  'consistent-return': ['error'],
  'consistent-this': ['error', 'self'],
  curly: ['error'],
  'default-case': ['error'],
  'default-case-last': ['error'],
  'default-param-last': ['error'],
  'dot-notation': ['error'],
  eqeqeq: ['error'],
  'func-name-matching': ['error'],
  'func-names': ['error', 'never'],
  'func-style': ['error', 'expression'],
  'grouped-accessor-pairs': [2, 'getBeforeSet'],
  'guard-for-in': ['error'],
  'id-denylist': ['off'],
  'id-length': ['off'],
  'id-match': ['off'],
  'init-declarations': ['off'],
  'logical-assignment-operators': [
    'error',
    'always',
    {
      enforceForIfStatements: true
    }
  ],
  'max-classes-per-file': ['off'],
  'max-depth': ['warn', 5],
  'max-lines': ['warn', 1_000],
  'max-lines-per-function': ['warn', 200],
  'max-nested-callbacks': ['warn', 3],
  'max-params': ['warn', 3],
  'max-statements': ['off'],
  'new-cap': [
    'error',
    {
      capIsNew: false,
      capIsNewExceptions: ['Intl'],
      newIsCap: true
    }
  ],
  'no-alert': ['error'],
  'no-array-constructor': ['error'],
  'no-bitwise': ['error'],
  'no-caller': ['error'],
  'no-case-declarations': ['error'],
  'no-console': ['error'],
  'no-continue': ['off'],
  'no-delete-var': ['error'],
  'no-div-regex': ['error'],
  'no-else-return': ['off'],
  'no-empty': ['error'],
  'no-empty-function': ['error'],
  'no-empty-static-block': ['error'],
  'no-eq-null': ['error'],
  'no-eval': ['error'],
  'no-extend-native': ['error'],
  'no-extra-bind': ['error'],
  'no-extra-boolean-cast': ['error'],
  'no-extra-label': ['error'],
  'no-global-assign': ['error'],
  'no-implicit-coercion': ['error'],
  'no-implicit-globals': ['error'],
  'no-implied-eval': ['error'],
  'no-inline-comments': ['off'],
  'no-invalid-this': ['error'],
  'no-iterator': ['error'],
  'no-label-var': ['error'],
  'no-labels': ['off'],
  'no-lone-blocks': ['error'],
  'no-lonely-if': ['error'],
  'no-loop-func': ['error'],
  'no-magic-numbers': ['off'],
  'no-multi-assign': ['error'],
  'no-multi-str': ['off'],
  'no-negated-condition': ['off'], // Disabled in favor of 'unicorn/no-negated-condition'
  'no-nested-ternary': ['off'], // Disabled in favor of 'unicorn/no-nested-ternary'
  'no-new': ['error'],
  'no-new-func': ['error'],
  'no-new-wrappers': ['error'],
  'no-nonoctal-decimal-escape': ['error'],
  'no-object-constructor': ['error'],
  'no-octal': ['error'],
  'no-octal-escape': ['error'],
  'no-param-reassign': ['error'],
  'no-plusplus': ['off'],
  'no-proto': ['error'],
  'no-redeclare': ['error'],
  'no-regex-spaces': ['error'],
  'no-restricted-exports': ['off'],
  'no-restricted-globals': ['off'],
  'no-restricted-imports': ['off'],
  'no-restricted-properties': ['off'],
  'no-restricted-syntax': ['off'],
  'no-return-assign': ['error'],
  'no-script-url': ['error'],
  'no-sequences': ['error'],
  'no-shadow': [
    'error',
    {
      allow: [
        'event',
        'length',
        'name',
        'status'
      ],
      builtinGlobals: false,
      hoist: 'all'
    }
  ],
  'no-shadow-restricted-names': ['error'],
  'no-ternary': ['off'],
  'no-throw-literal': ['error'],
  'no-undef-init': ['error'],
  'no-undefined': ['off'],
  'no-underscore-dangle': ['off'],
  'no-unneeded-ternary': ['error'],
  'no-unused-expressions': ['error'],
  'no-unused-labels': ['error'],
  'no-useless-call': ['error'],
  'no-useless-catch': ['error'],
  'no-useless-computed-key': ['error'],
  'no-useless-concat': ['error'],
  'no-useless-constructor': ['error'],
  'no-useless-escape': ['error'],
  'no-useless-rename': ['error'],
  'no-useless-return': ['error'],
  'no-var': ['error'],
  'no-void': [
    'error',
    {
      allowAsStatement: true
    }
  ],
  'no-warning-comments': ['warn'], // Should this be enabled alongside 'unicorn/expiring-todo-comments'?
  'no-with': ['error'],
  'object-shorthand': ['error'],
  'one-var': ['error', 'never'],
  'operator-assignment': ['error'],
  'prefer-arrow-callback': ['error'],
  'prefer-const': ['error'],
  'prefer-destructuring': ['off'],
  'prefer-exponentiation-operator': ['error'],
  'prefer-named-capture-group': ['off'],
  'prefer-numeric-literals': ['error'],
  'prefer-object-has-own': ['error'],
  'prefer-object-spread': ['error'],
  'prefer-promise-reject-errors': ['error'],
  'prefer-regex-literals': [
    'error',
    {
      disallowRedundantWrapping: true
    }
  ],
  'prefer-rest-params': ['error'],
  'prefer-spread': ['error'],
  'prefer-template': ['error'],
  radix: ['error', 'as-needed'],
  'require-await': ['error'], // Should this be enabled?
  'require-unicode-regexp': ['error'],
  'require-yield': ['error'],
  'sort-imports': ['off'],
  'sort-keys': ['off'],
  'sort-vars': ['off'],
  strict: ['error', 'never'],
  'symbol-description': ['error'],
  'vars-on-top': ['error'],
  yoda: ['error']
} satisfies Linter.Config['rules'];

const eslintLayoutRules = {
  'unicode-bom': ['error']
} satisfies Linter.Config['rules'];

const unicornRules = {
  'unicorn/better-regex': ['error'],
  'unicorn/catch-error-name': ['error', { name: 'error' }],
  'unicorn/consistent-assert': ['off'],
  'unicorn/consistent-date-clone': ['error'],
  'unicorn/consistent-destructuring': ['error'],
  'unicorn/consistent-empty-array-spread': ['error'],
  'unicorn/consistent-existence-index-check': ['error'],
  'unicorn/consistent-function-scoping': ['error'],
  'unicorn/consistent-template-literal-escape': ['error'],
  'unicorn/custom-error-definition': ['error'],
  'unicorn/empty-brace-spaces': ['error'],
  'unicorn/error-message': ['error'],
  'unicorn/escape-case': ['error'],
  'unicorn/expiring-todo-comments': ['warn'],
  'unicorn/explicit-length-check': ['error'],
  'unicorn/filename-case': [
    'error',
    {
      cases: {
        camelCase: true,
        kebabCase: true,
        pascalCase: true,
        snakeCase: true
      }
    }
  ],
  'unicorn/import-style': ['off'],
  'unicorn/isolated-functions': ['off'],
  'unicorn/new-for-builtins': ['error'],
  'unicorn/no-abusive-eslint-disable': ['error'],
  'unicorn/no-accessor-recursion': ['error'],
  'unicorn/no-anonymous-default-export': ['error'],
  'unicorn/no-array-callback-reference': ['off'],
  'unicorn/no-array-for-each': ['error'],
  'unicorn/no-array-method-this-argument': ['error'],
  'unicorn/no-array-reduce': [
    'error',
    {
      allowSimpleOperations: true
    }
  ],
  'unicorn/no-array-reverse': ['error'],
  'unicorn/no-array-sort': ['off'],
  'unicorn/no-await-expression-member': ['error'],
  'unicorn/no-await-in-promise-methods': ['error'],
  'unicorn/no-console-spaces': ['error'],
  'unicorn/no-document-cookie': ['error'],
  'unicorn/no-empty-file': ['error'],
  'unicorn/no-for-loop': ['error'],
  'unicorn/no-hex-escape': ['error'],
  'unicorn/no-immediate-mutation': ['error'],
  'unicorn/no-instanceof-builtins': ['error'],
  'unicorn/no-invalid-fetch-options': ['error'],
  'unicorn/no-invalid-remove-event-listener': ['error'],
  'unicorn/no-keyword-prefix': ['off'],
  'unicorn/no-lonely-if': ['error'],
  'unicorn/no-magic-array-flat-depth': ['error'],
  'unicorn/no-named-default': ['error'],
  'unicorn/no-negated-condition': ['error'],
  'unicorn/no-negation-in-equality-check': ['error'],
  'unicorn/no-nested-ternary': ['error'],
  'unicorn/no-new-array': ['error'],
  'unicorn/no-new-buffer': ['error'],
  'unicorn/no-null': ['off'],
  'unicorn/no-object-as-default-parameter': ['error'],
  'unicorn/no-single-promise-in-promise-methods': ['error'],
  'unicorn/no-static-only-class': ['error'],
  'unicorn/no-thenable': ['error'],
  'unicorn/no-this-assignment': ['error'],
  'unicorn/no-typeof-undefined': ['error'],
  'unicorn/no-unnecessary-array-flat-depth': ['error'],
  'unicorn/no-unnecessary-array-splice-count': ['error'],
  'unicorn/no-unnecessary-await': ['error'],
  'unicorn/no-unnecessary-polyfills': ['error'],
  'unicorn/no-unnecessary-slice-end': ['error'],
  'unicorn/no-unreadable-array-destructuring': ['error'],
  'unicorn/no-unreadable-iife': ['error'],
  'unicorn/no-unused-properties': ['error'],
  'unicorn/no-useless-collection-argument': ['error'],
  'unicorn/no-useless-error-capture-stack-trace': ['error'],
  'unicorn/no-useless-fallback-in-spread': ['error'],
  'unicorn/no-useless-iterator-to-array': ['error'],
  'unicorn/no-useless-length-check': ['error'],
  'unicorn/no-useless-promise-resolve-reject': ['error'],
  'unicorn/no-useless-spread': ['error'],
  'unicorn/no-useless-switch-case': ['error'],
  'unicorn/no-useless-undefined': ['error'],
  'unicorn/no-zero-fractions': ['error'],
  'unicorn/number-literal-case': ['error'],
  'unicorn/numeric-separators-style': [
    2,
    {
      number: {
        groupLength: 3,
        minimumDigits: 0
      }
    }
  ],
  'unicorn/prefer-add-event-listener': ['error'], // Should this be enabled?
  'unicorn/prefer-array-find': ['error'],
  'unicorn/prefer-array-flat': ['error'],
  'unicorn/prefer-array-flat-map': ['error'],
  'unicorn/prefer-array-index-of': ['error'],
  'unicorn/prefer-array-some': ['error'],
  'unicorn/prefer-at': ['error'],
  'unicorn/prefer-bigint-literals': ['error'],
  'unicorn/prefer-blob-reading-methods': ['error'],
  'unicorn/prefer-class-fields': ['error'],
  'unicorn/prefer-classlist-toggle': ['error'],
  'unicorn/prefer-code-point': ['error'],
  'unicorn/prefer-date-now': ['error'],
  'unicorn/prefer-default-parameters': ['error'],
  'unicorn/prefer-event-target': ['error'],
  'unicorn/prefer-export-from': ['error'],
  'unicorn/prefer-global-this': ['off'],
  'unicorn/prefer-import-meta-properties': ['error'],
  'unicorn/prefer-includes': ['error'],
  'unicorn/prefer-logical-operator-over-ternary': ['error'],
  'unicorn/prefer-math-min-max': ['error'],
  'unicorn/prefer-math-trunc': ['error'],
  'unicorn/prefer-modern-math-apis': ['error'],
  'unicorn/prefer-native-coercion-functions': ['error'],
  'unicorn/prefer-negative-index': ['error'],
  'unicorn/prefer-number-properties': ['error'],
  'unicorn/prefer-object-from-entries': ['error'],
  'unicorn/prefer-optional-catch-binding': ['error'],
  'unicorn/prefer-prototype-methods': ['error'],
  'unicorn/prefer-reflect-apply': ['error'],
  'unicorn/prefer-regexp-test': ['error'],
  'unicorn/prefer-response-static-json': ['error'],
  'unicorn/prefer-set-has': ['error'],
  'unicorn/prefer-set-size': ['error'],
  'unicorn/prefer-simple-condition-first': ['error'],
  'unicorn/prefer-single-call': ['error'],
  'unicorn/prefer-spread': ['off'], // Should this be disabled?
  'unicorn/prefer-string-raw': ['error'],
  'unicorn/prefer-string-replace-all': ['error'],
  'unicorn/prefer-string-slice': ['error'],
  'unicorn/prefer-string-starts-ends-with': ['error'],
  'unicorn/prefer-string-trim-start-end': ['error'],
  'unicorn/prefer-structured-clone': ['error'],
  'unicorn/prefer-switch': ['error'],
  'unicorn/prefer-ternary': ['error'],
  'unicorn/prefer-type-error': ['error'],
  'unicorn/prevent-abbreviations': ['off'], // Revisit this rule
  'unicorn/relative-url-style': ['error'],
  'unicorn/require-array-join-separator': ['error'],
  'unicorn/require-module-attributes': ['error'],
  'unicorn/require-module-specifiers': ['off'],
  'unicorn/require-number-to-fixed-digits-argument': ['error'],
  'unicorn/string-content': ['off'],
  'unicorn/switch-case-braces': ['error', 'avoid'],
  'unicorn/switch-case-break-position': ['error'],
  'unicorn/template-indent': ['error'],
  'unicorn/text-encoding-identifier-case': ['error'],
  'unicorn/throw-new-error': ['error']
} satisfies Linter.Config['rules'];

const regexpRules = {
  'regexp/confusing-quantifier': ['error'],
  'regexp/control-character-escape': ['error'],
  'regexp/grapheme-string-literal': ['error'],
  'regexp/hexadecimal-escape': [
    'error',
    'never'
  ],
  'regexp/letter-case': [
    'error',
    {
      caseInsensitive: 'lowercase',
      controlEscape: 'uppercase',
      hexadecimalEscape: 'uppercase',
      unicodeEscape: 'uppercase'
    }
  ],
  'regexp/match-any': ['error'],
  'regexp/negation': ['error'],
  'regexp/no-contradiction-with-assertion': ['error'],
  'regexp/no-control-character': ['error'],
  'regexp/no-dupe-characters-character-class': ['error'],
  'regexp/no-dupe-disjunctions': ['error'],
  'regexp/no-empty-alternative': ['error'],
  'regexp/no-empty-capturing-group': ['error'],
  'regexp/no-empty-character-class': ['error'],
  'regexp/no-empty-group': ['error'],
  'regexp/no-empty-lookarounds-assertion': ['error'],
  'regexp/no-empty-string-literal': ['error'],
  'regexp/no-escape-backspace': ['error'],
  'regexp/no-extra-lookaround-assertions': ['error'],
  'regexp/no-invalid-regexp': ['error'],
  'regexp/no-invisible-character': ['error'],
  'regexp/no-lazy-ends': ['error'],
  'regexp/no-legacy-features': ['error'],
  'regexp/no-misleading-capturing-group': ['error'],
  'regexp/no-misleading-unicode-character': ['error'],
  'regexp/no-missing-g-flag': ['error'],
  'regexp/no-non-standard-flag': ['error'],
  'regexp/no-obscure-range': ['error'],
  'regexp/no-octal': ['error'],
  'regexp/no-optional-assertion': ['error'],
  'regexp/no-potentially-useless-backreference': ['error'],
  'regexp/no-standalone-backslash': ['error'],
  'regexp/no-super-linear-backtracking': ['error'],
  'regexp/no-super-linear-move': ['error'],
  'regexp/no-trivially-nested-assertion': ['error'],
  'regexp/no-trivially-nested-quantifier': ['error'],
  'regexp/no-unused-capturing-group': ['error'],
  'regexp/no-useless-assertions': ['error'],
  'regexp/no-useless-backreference': ['error'],
  'regexp/no-useless-character-class': ['error'],
  'regexp/no-useless-dollar-replacements': ['error'],
  'regexp/no-useless-escape': ['error'],
  'regexp/no-useless-flag': ['error'],
  'regexp/no-useless-lazy': ['error'],
  'regexp/no-useless-non-capturing-group': ['error'],
  'regexp/no-useless-quantifier': ['error'],
  'regexp/no-useless-range': ['error'],
  'regexp/no-useless-set-operand': ['error'],
  'regexp/no-useless-string-literal': ['error'],
  'regexp/no-useless-two-nums-quantifier': ['error'],
  'regexp/no-zero-quantifier': ['error'],
  'regexp/optimal-lookaround-quantifier': ['error'],
  'regexp/optimal-quantifier-concatenation': ['error'],
  'regexp/prefer-character-class': ['error'],
  'regexp/prefer-d': ['error'],
  'regexp/prefer-escape-replacement-dollar-char': ['error'],
  'regexp/prefer-lookaround': ['error'],
  'regexp/prefer-named-backreference': ['error'],
  'regexp/prefer-named-capture-group': ['error'],
  'regexp/prefer-named-replacement': ['error'],
  'regexp/prefer-plus-quantifier': ['error'],
  'regexp/prefer-predefined-assertion': ['error'],
  'regexp/prefer-quantifier': ['error'],
  'regexp/prefer-question-quantifier': ['error'],
  'regexp/prefer-range': ['error'],
  'regexp/prefer-regexp-exec': ['error'],
  'regexp/prefer-regexp-test': ['error'],
  'regexp/prefer-result-array-groups': ['error'],
  'regexp/prefer-set-operation': ['error'],
  'regexp/prefer-star-quantifier': ['error'],
  'regexp/prefer-unicode-codepoint-escapes': ['error'],
  'regexp/prefer-w': ['error'],
  'regexp/require-unicode-regexp': ['off'],
  'regexp/require-unicode-sets-regexp': ['off'],
  'regexp/simplify-set-operations': ['error'],
  'regexp/sort-alternatives': ['error'],
  'regexp/sort-character-class-elements': ['off'],
  'regexp/sort-flags': ['error'],
  'regexp/strict': ['error'],
  'regexp/unicode-escape': [
    'error',
    'unicodeEscape'
  ],
  'regexp/unicode-property': [
    'error',
    {
      generalCategory: 'never',
      key: 'long',
      property: 'long'
    }
  ],
  'regexp/use-ignore-case': ['error']
} satisfies Linter.Config['rules'];

const promiseRules = {
  'promise/always-return': ['error'],
  'promise/avoid-new': ['off'],
  'promise/catch-or-return': [
    'error',
    {
      allowFinally: true
    }
  ],
  'promise/no-callback-in-promise': ['error'],
  'promise/no-multiple-resolved': ['error'],
  'promise/no-native': ['off'],
  'promise/no-nesting': ['error'],
  'promise/no-new-statics': ['error'],
  'promise/no-promise-in-callback': ['error'],
  'promise/no-return-in-finally': ['error'],
  'promise/no-return-wrap': ['error'],
  'promise/param-names': ['error'],
  'promise/prefer-await-to-callbacks': ['off'],
  'promise/prefer-await-to-then': ['off'],
  'promise/prefer-catch': ['error'],
  'promise/spec-only': ['error'],
  'promise/valid-params': ['error']
} satisfies Linter.Config['rules'];

const importXRules = {
  'import-x/consistent-type-specifier-style': ['off'], // Handled by @typescript-eslint/consistent-type-imports
  'import-x/default': ['error'],
  'import-x/dynamic-import-chunkname': ['off'],
  'import-x/export': ['error'],
  'import-x/exports-last': ['off'],
  'import-x/extensions': ['off'],
  'import-x/first': ['error'],
  'import-x/group-exports': ['off'],
  'import-x/max-dependencies': ['off'],
  'import-x/named': ['off'],
  'import-x/namespace': ['error'],
  'import-x/newline-after-import': ['error'],
  'import-x/no-absolute-path': ['error'],
  'import-x/no-amd': ['error'],
  'import-x/no-anonymous-default-export': ['error'],
  'import-x/no-commonjs': ['off'],
  'import-x/no-cycle': ['error'],
  'import-x/no-default-export': ['off'],
  'import-x/no-deprecated': ['off'], // Handled by @typescript-eslint/no-deprecated
  'import-x/no-duplicates': ['error'],
  'import-x/no-dynamic-require': ['error'],
  'import-x/no-empty-named-blocks': ['error'],
  'import-x/no-extraneous-dependencies': ['error'],
  'import-x/no-import-module-exports': ['error'],
  'import-x/no-internal-modules': ['off'],
  'import-x/no-mutable-exports': ['error'],
  'import-x/no-named-as-default': ['error'],
  'import-x/no-named-as-default-member': ['off'],
  'import-x/no-named-default': ['error'],
  'import-x/no-named-export': ['off'],
  'import-x/no-namespace': ['off'],
  'import-x/no-nodejs-modules': ['off'],
  'import-x/no-relative-packages': ['off'],
  'import-x/no-relative-parent-imports': ['off'],
  'import-x/no-rename-default': ['off'],
  'import-x/no-restricted-paths': ['off'],
  'import-x/no-self-import': ['error'],
  'import-x/no-unassigned-import': ['off'],
  'import-x/no-unresolved': ['error', { commonjs: true }],
  'import-x/no-unused-modules': ['off'],
  'import-x/no-useless-path-segments': ['error', { noUselessIndex: false }],
  'import-x/no-webpack-loader-syntax': ['error'],
  'import-x/order': ['off'], // Handled by perfectionist/sort-imports
  'import-x/prefer-default-export': ['off'],
  'import-x/prefer-namespace-import': ['off'],
  'import-x/unambiguous': ['off']
} satisfies Linter.Config['rules'];

const securityRules = {
  'security/detect-bidi-characters': ['error'],
  'security/detect-buffer-noassert': ['off'],
  'security/detect-child-process': ['error'],
  'security/detect-disable-mustache-escape': ['off'],
  'security/detect-eval-with-expression': ['error'],
  'security/detect-new-buffer': ['off'],
  'security/detect-no-csrf-before-method-override': ['off'],
  'security/detect-non-literal-fs-filename': ['error'],
  'security/detect-non-literal-regexp': ['error'],
  'security/detect-non-literal-require': ['error'],
  'security/detect-object-injection': ['off'],
  'security/detect-possible-timing-attacks': ['off'],
  'security/detect-pseudoRandomBytes': ['off'],
  'security/detect-unsafe-regex': ['off']
} satisfies Linter.Config['rules'];

const sonarjsRules = {
  'sonarjs/anchor-precedence': ['error'],
  'sonarjs/argument-type': ['error'],
  'sonarjs/arguments-order': ['error'],
  'sonarjs/arguments-usage': ['error'],
  'sonarjs/array-callback-without-return': ['error'],
  'sonarjs/array-constructor': ['error'],
  'sonarjs/arrow-function-convention': ['off'],
  'sonarjs/assertions-in-tests': ['error'],
  'sonarjs/aws-apigateway-public-api': ['off'],
  'sonarjs/aws-ec2-rds-dms-public': ['off'],
  'sonarjs/aws-ec2-unencrypted-ebs-volume': ['off'],
  'sonarjs/aws-efs-unencrypted': ['off'],
  'sonarjs/aws-iam-all-privileges': ['off'],
  'sonarjs/aws-iam-all-resources-accessible': ['off'],
  'sonarjs/aws-iam-privilege-escalation': ['off'],
  'sonarjs/aws-iam-public-access': ['off'],
  'sonarjs/aws-opensearchservice-domain': ['off'],
  'sonarjs/aws-rds-unencrypted-databases': ['off'],
  'sonarjs/aws-restricted-ip-admin-access': ['off'],
  'sonarjs/aws-s3-bucket-granted-access': ['off'],
  'sonarjs/aws-s3-bucket-insecure-http': ['off'],
  'sonarjs/aws-s3-bucket-public-access': ['off'],
  'sonarjs/aws-s3-bucket-versioning': ['off'],
  'sonarjs/aws-sagemaker-unencrypted-notebook': ['off'],
  'sonarjs/aws-sns-unencrypted-topics': ['off'],
  'sonarjs/aws-sqs-unencrypted-queue': ['off'],
  'sonarjs/bitwise-operators': ['error'],
  'sonarjs/block-scoped-var': ['off'],
  'sonarjs/bool-param-default': ['off'],
  'sonarjs/call-argument-line': ['error'],
  'sonarjs/chai-determinate-assertion': ['error'],
  'sonarjs/class-name': ['error'],
  'sonarjs/class-prototype': ['error'],
  'sonarjs/code-eval': ['error'],
  'sonarjs/cognitive-complexity': ['error'],
  'sonarjs/comma-or-logical-or-case': ['error'],
  'sonarjs/comment-regex': ['off'],
  'sonarjs/concise-regex': ['off'],
  'sonarjs/confidential-information-logging': ['error'],
  'sonarjs/constructor-for-side-effects': ['error'],
  'sonarjs/content-length': ['error'],
  'sonarjs/content-security-policy': ['error'],
  'sonarjs/cookie-no-httponly': ['error'],
  'sonarjs/cors': ['error'],
  'sonarjs/csrf': ['error'],
  'sonarjs/cyclomatic-complexity': ['off'],
  'sonarjs/declarations-in-global-scope': ['off'],
  'sonarjs/deprecation': ['off'],
  'sonarjs/destructuring-assignment-syntax': ['off'],
  'sonarjs/different-types-comparison': ['error'],
  'sonarjs/disabled-auto-escaping': ['error'],
  'sonarjs/disabled-resource-integrity': ['error'],
  'sonarjs/disabled-timeout': ['error'],
  'sonarjs/dompurify-unsafe-config': ['error'],
  'sonarjs/duplicates-in-character-class': ['off'],
  'sonarjs/dynamically-constructed-templates': ['error'],
  'sonarjs/elseif-without-else': ['off'],
  'sonarjs/empty-string-repetition': ['error'],
  'sonarjs/encryption-secure-mode': ['error'],
  'sonarjs/existing-groups': ['error'],
  'sonarjs/expression-complexity': ['off'],
  'sonarjs/file-header': ['off'],
  'sonarjs/file-name-differ-from-class': ['off'],
  'sonarjs/file-permissions': ['error'],
  'sonarjs/file-uploads': ['error'],
  'sonarjs/fixme-tag': ['off'],
  'sonarjs/for-in': ['off'],
  'sonarjs/for-loop-increment-sign': ['error'],
  'sonarjs/frame-ancestors': ['error'],
  'sonarjs/function-inside-loop': ['error'],
  'sonarjs/function-name': ['off'],
  'sonarjs/function-return-type': ['error'],
  'sonarjs/future-reserved-words': ['error'],
  'sonarjs/generator-without-yield': ['error'],
  'sonarjs/hardcoded-secret-signatures': ['error'],
  'sonarjs/hashing': ['error'],
  'sonarjs/hidden-files': ['error'],
  'sonarjs/in-operator-type-error': ['error'],
  'sonarjs/inconsistent-function-call': ['error'],
  'sonarjs/index-of-compare-to-positive-number': ['error'],
  'sonarjs/insecure-cookie': ['error'],
  'sonarjs/insecure-jwt-token': ['error'],
  'sonarjs/inverted-assertion-arguments': ['error'],
  'sonarjs/jsx-no-leaked-render': ['off'],
  'sonarjs/label-position': ['error'],
  'sonarjs/link-with-target-blank': ['error'],
  'sonarjs/max-lines': ['off'],
  'sonarjs/max-lines-per-function': ['off'],
  'sonarjs/max-switch-cases': ['error'],
  'sonarjs/max-union-size': ['off'],
  'sonarjs/misplaced-loop-counter': ['error'],
  'sonarjs/nested-control-flow': ['error', { maximumNestingLevel: 4 }],
  'sonarjs/new-operator-misuse': ['error'],
  'sonarjs/no-all-duplicated-branches': ['error'],
  'sonarjs/no-alphabetical-sort': ['error'],
  'sonarjs/no-angular-bypass-sanitization': ['off'],
  'sonarjs/no-array-delete': ['error'],
  'sonarjs/no-associative-arrays': ['error'],
  'sonarjs/no-async-constructor': ['error'],
  'sonarjs/no-built-in-override': ['error'],
  'sonarjs/no-case-label-in-switch': ['error'],
  'sonarjs/no-clear-text-protocols': ['error'],
  'sonarjs/no-code-after-done': ['error'],
  'sonarjs/no-collapsible-if': ['error'],
  'sonarjs/no-collection-size-mischeck': ['error'],
  'sonarjs/no-commented-code': ['off'],
  'sonarjs/no-control-regex': ['off'],
  'sonarjs/no-dead-store': ['error'],
  'sonarjs/no-delete-var': ['off'],
  'sonarjs/no-duplicate-in-composite': ['error'],
  'sonarjs/no-duplicate-string': ['error', { threshold: 5 }],
  'sonarjs/no-duplicated-branches': ['error'],
  'sonarjs/no-element-overwrite': ['error'],
  'sonarjs/no-empty-after-reluctant': ['error'],
  'sonarjs/no-empty-alternatives': ['off'],
  'sonarjs/no-empty-character-class': ['off'],
  'sonarjs/no-empty-collection': ['error'],
  'sonarjs/no-empty-group': ['off'],
  'sonarjs/no-empty-test-file': ['error'],
  'sonarjs/no-equals-in-for-termination': ['error'],
  'sonarjs/no-exclusive-tests': ['error'],
  'sonarjs/no-extra-arguments': ['error'],
  'sonarjs/no-fallthrough': ['off'],
  'sonarjs/no-for-in-iterable': ['error'],
  'sonarjs/no-function-declaration-in-block': ['error'],
  'sonarjs/no-global-this': ['error'],
  'sonarjs/no-globals-shadowing': ['error'],
  'sonarjs/no-gratuitous-expressions': ['error'],
  'sonarjs/no-hardcoded-ip': ['error'],
  'sonarjs/no-hardcoded-passwords': ['error'],
  'sonarjs/no-hardcoded-secrets': ['error'],
  'sonarjs/no-hook-setter-in-body': ['off'],
  'sonarjs/no-identical-conditions': ['error'],
  'sonarjs/no-identical-expressions': ['error'],
  'sonarjs/no-identical-functions': ['error'],
  'sonarjs/no-ignored-exceptions': ['error'],
  'sonarjs/no-ignored-return': ['error'],
  'sonarjs/no-implicit-dependencies': ['off'],
  'sonarjs/no-implicit-global': ['error'],
  'sonarjs/no-in-misuse': ['error'],
  'sonarjs/no-incomplete-assertions': ['error'],
  'sonarjs/no-inconsistent-returns': ['error'],
  'sonarjs/no-incorrect-string-concat': ['error'],
  'sonarjs/no-internal-api-use': ['error'],
  'sonarjs/no-intrusive-permissions': ['error'],
  'sonarjs/no-invalid-regexp': ['off'],
  'sonarjs/no-invariant-returns': ['error'],
  'sonarjs/no-inverted-boolean-check': ['error'],
  'sonarjs/no-ip-forward': ['error'],
  'sonarjs/no-labels': ['off'],
  'sonarjs/no-literal-call': ['error'],
  'sonarjs/no-mime-sniff': ['error'],
  'sonarjs/no-misleading-array-reverse': ['error'],
  'sonarjs/no-misleading-character-class': ['off'],
  'sonarjs/no-mixed-content': ['error'],
  'sonarjs/no-nested-assignment': ['error'],
  'sonarjs/no-nested-conditional': ['error'],
  'sonarjs/no-nested-functions': ['error'],
  'sonarjs/no-nested-incdec': ['error'],
  'sonarjs/no-nested-switch': ['error'],
  'sonarjs/no-nested-template-literals': ['error'],
  'sonarjs/no-os-command-from-path': ['error'],
  'sonarjs/no-parameter-reassignment': ['off'],
  'sonarjs/no-primitive-wrappers': ['error'],
  'sonarjs/no-redundant-assignments': ['error'],
  'sonarjs/no-redundant-boolean': ['error'],
  'sonarjs/no-redundant-jump': ['error'],
  'sonarjs/no-redundant-optional': ['error'],
  'sonarjs/no-reference-error': ['error'],
  'sonarjs/no-referrer-policy': ['error'],
  'sonarjs/no-regex-spaces': ['off'],
  'sonarjs/no-require-or-define': ['error'],
  'sonarjs/no-return-type-any': ['error'],
  'sonarjs/no-same-argument-assert': ['error'],
  'sonarjs/no-same-line-conditional': ['error'],
  'sonarjs/no-selector-parameter': ['error'],
  'sonarjs/no-session-cookies-on-static-assets': ['error'],
  'sonarjs/no-skipped-tests': ['error'],
  'sonarjs/no-small-switch': ['error'],
  'sonarjs/no-sonar-comments': ['off'],
  'sonarjs/no-table-as-layout': ['off'],
  'sonarjs/no-try-promise': ['error'],
  'sonarjs/no-undefined-argument': ['error'],
  'sonarjs/no-undefined-assignment': ['off'],
  'sonarjs/no-unenclosed-multiline-block': ['error'],
  'sonarjs/no-uniq-key': ['off'],
  'sonarjs/no-unthrown-error': ['error'],
  'sonarjs/no-unused-collection': ['error'],
  'sonarjs/no-unused-function-argument': ['off'],
  'sonarjs/no-unused-vars': ['off'],
  'sonarjs/no-use-of-empty-return-value': ['error'],
  'sonarjs/no-useless-catch': ['off'],
  'sonarjs/no-useless-increment': ['error'],
  'sonarjs/no-useless-intersection': ['error'],
  'sonarjs/no-useless-react-setstate': ['off'],
  'sonarjs/no-variable-usage-before-declaration': ['error'],
  'sonarjs/no-weak-cipher': ['error'],
  'sonarjs/no-weak-keys': ['error'],
  'sonarjs/no-wildcard-import': ['off'],
  'sonarjs/non-existent-operator': ['error'],
  'sonarjs/non-number-in-arithmetic-expression': ['error'],
  'sonarjs/null-dereference': ['error'],
  'sonarjs/object-alt-content': ['off'],
  'sonarjs/operation-returning-nan': ['error'],
  'sonarjs/os-command': ['error'],
  'sonarjs/post-message': ['error'],
  'sonarjs/prefer-default-last': ['error'],
  'sonarjs/prefer-immediate-return': ['error'],
  'sonarjs/prefer-object-literal': ['error'],
  'sonarjs/prefer-promise-shorthand': ['error'],
  'sonarjs/prefer-read-only-props': ['off'],
  'sonarjs/prefer-regexp-exec': ['off'],
  'sonarjs/prefer-single-boolean-return': ['error'],
  'sonarjs/prefer-type-guard': ['error'],
  'sonarjs/prefer-while': ['error'],
  'sonarjs/production-debug': ['error'],
  'sonarjs/pseudo-random': ['error'],
  'sonarjs/public-static-readonly': ['error'],
  'sonarjs/publicly-writable-directories': ['error'],
  'sonarjs/reduce-initial-value': ['error'],
  'sonarjs/redundant-type-aliases': ['error'],
  'sonarjs/regex-complexity': ['error'],
  'sonarjs/review-blockchain-mnemonic': ['off'],
  'sonarjs/session-regeneration': ['error'],
  'sonarjs/shorthand-property-grouping': ['off'],
  'sonarjs/single-char-in-character-classes': ['off'],
  'sonarjs/single-character-alternation': ['off'],
  'sonarjs/slow-regex': ['off'],
  'sonarjs/sql-queries': ['error'],
  'sonarjs/stable-tests': ['error'],
  'sonarjs/stateful-regex': ['error'],
  'sonarjs/strict-transport-security': ['error'],
  'sonarjs/strings-comparison': ['off'],
  'sonarjs/table-header': ['off'],
  'sonarjs/table-header-reference': ['off'],
  'sonarjs/test-check-exception': ['error'],
  'sonarjs/todo-tag': ['off'],
  'sonarjs/too-many-break-or-continue-in-loop': ['off'],
  'sonarjs/unicode-aware-regex': ['off'],
  'sonarjs/unused-import': ['off'],
  'sonarjs/unused-named-groups': ['off'],
  'sonarjs/unverified-certificate': ['error'],
  'sonarjs/unverified-hostname': ['error'],
  'sonarjs/updated-const-var': ['error'],
  'sonarjs/updated-loop-counter': ['error'],
  'sonarjs/use-type-alias': ['error'],
  'sonarjs/values-not-convertible-to-numbers': ['error'],
  'sonarjs/variable-name': ['off'],
  'sonarjs/void-use': ['error'],
  'sonarjs/weak-ssl': ['error'],
  'sonarjs/x-powered-by': ['error'],
  'sonarjs/xml-parser-xxe': ['error']
} satisfies Linter.Config['rules'];

const eslintCommentsRules = {
  '@eslint-community/eslint-comments/disable-enable-pair': ['error', { allowWholeFile: true }],
  '@eslint-community/eslint-comments/no-aggregating-enable': ['error'],
  '@eslint-community/eslint-comments/no-duplicate-disable': ['error'],
  '@eslint-community/eslint-comments/no-restricted-disable': ['off'],
  '@eslint-community/eslint-comments/no-unlimited-disable': ['error'],
  '@eslint-community/eslint-comments/no-unused-enable': ['error'],
  '@eslint-community/eslint-comments/no-use': ['off'],
  '@eslint-community/eslint-comments/require-description': ['error']
} satisfies Linter.Config['rules'];

const unusedImportsRules = {
  'unused-imports/no-unused-imports': ['error'],
  'unused-imports/no-unused-vars': ['off']
} satisfies Linter.Config['rules'];

export default {
  ...eslintCommentsRules,
  ...eslintRules,
  ...eslintSuggestionsRules,
  ...eslintLayoutRules,
  ...importXRules,
  ...promiseRules,
  ...regexpRules,
  ...securityRules,
  ...sonarjsRules,
  ...unicornRules,
  ...unusedImportsRules
} satisfies Linter.Config['rules'];
